### ISSUE TITLE
Please consider adding our CVPR 2022 paper TVConv to the Model Acceleration category

### ISSUE THREAD

**Issue by JierunChen** [ChanChiChoi/awesome-Face_Recognition#8]
Please consider adding our CVPR 2022 paper TVConv to the Model Acceleration category. Many thanks.

TVConv: Efficient Translation Variant Convolution for Layout-aware Visual Processing

Paper: http://arxiv.org/abs/2203.10489
Code: https://github.com/JierunChen/TVConv

**Comment by Enki08** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到，我会尽快给您回复。

**Comment by qiuhaining** [comment]
收到了！谢谢！

**Comment by ChanChiChoi** [comment]
> 

ok

**Comment by qiuhaining** [comment]
收到了！谢谢！
